# Generated by Django 3.2 on 2021-04-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacttuber', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacttubers',
            old_name='meassage',
            new_name='message',
        ),
    ]
