# Generated by Django 3.2 on 2021-04-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('fb_link', models.CharField(blank=True, max_length=255)),
                ('insta_link', models.CharField(blank=True, max_length=255)),
                ('tweeter_link', models.CharField(blank=True, max_length=255)),
                ('ytube_link', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
