# Generated by Django 3.2 on 2021-04-08 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
